Parameters:
  pDbName:
    Type: String
    Default: test
  dbSecretName:
    Type: String
    Default: testdb_testsecret

Resources:
  testDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref pDbName
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.small
      StorageType: gp2
      Engine: postgres
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref dbSecretName, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref dbSecretName, ':SecretString:password}}' ]]
      DBInstanceIdentifier: !Join ["-", [!Ref pDbName, !Ref "AWS::Region"]]
